[workspace]
members = [
    "api",
]

[workspace.dependencies]
actix = "0.13"
actix-cors = "0.6"
actix-web = "4.3"
actix-web-actors = "4.1"
actix-web-lab = "0.19"
actix-ws = "0.2.5"

dotenv = "0.15"
env_logger = "0.10"
log = "0.4"